version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/app

permissions:
  - object: /var/www/app
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
