version: 0.2
phases:
  install:
    commands:
      - chmod +x scripts/clean.sh
      - chmod +x scripts/start_server.sh
  build:
    commands:
      - echo "Build complete"
artifacts:
  base-directory: source
  files:
    - '**/*'
